### PR TITLE
Fix placement of navbar

### LINKED ISSUE #53: Move the search input field to the center of the navbar
image

Use display: flex or something with "align-self: center" to vertically center the item. Not sure what caused it to move up

https://github.com/AutoPacker-OSS/AutoPacker/blob/6395fd09977396edae91d915dc59c477b8642006/web-application/src/components/Navbar/Navbar.js#L60

### PR DESCRIPTION
**Pull request by MrPrecise**
Added padding to move navbar to a more suited location

### CODE REVIEW

**Comment by ANicholasson** [comment]
If you can, try and use display flex with align-self:center to vertically center the item inside the container (navbar) depending on the container height.

**Review by ANicholasson — COMMENTED** [review]
If you can, try and use display flex with align-self:center to vertically center the item inside the container (navbar) depending on the container height.

**Comment by MrPrecise** [comment]
image

I can't get allign-self to work. I tried align:"center" with no sucess. Regardless I thought the navbar was a set size. Meaning if it don't scale I could just hardcode a padding.

**Comment by ANicholasson** [comment]
> image
> 
> I can't get allign-self to work. I tried align:"center" with no sucess. Regardless I thought the navbar was a set size. Meaning if it don't scale I could just hardcode a padding. 

Inline styling in JSX is a bit different then regular and uses camel case so it would be alignSelf: "center" instead. 

The wrapper also need to be of: display: "flex" to use "align self". If this messes up the styling you can merge in with padding👍

**Comment by MrPrecise** [comment]
image

With using display: "flex" gives me the opposite, I'll merge this with the hard set padding. If it yield problems in the future with this hard set padding, then I will look into another way to do it.

**Pull request merged**
